[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.23"
via_ir = true
optimizer = true
optimizer_runs = 200

# For dependencies
remappings = [
    "@ds-test/=lib/ds-test/src/",
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    "filecoin-solidity/=lib/filecoin-solidity/",
    "solidity-cborutils/=lib/solidity-cborutils/",
    "@ensdomains/buffer=lib/buffer/"
]

# Allow reading test data files
fs_permissions = [{ access = "read", path = "./test" }]

# Gas settings for Filecoin networks
gas_limit = 1000000
gas_price = 2000000000
